### ISSUE TITLE
ERROR in Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Grandmasg** [haoliangyu/angular2-leaflet-starter#10]
After running webpack i get this error in CMD:
"ERROR in Path must be a string. Received undefined"

The same text is also in the pulbic/index.html file

How to fix this?
![screenshot_3](https://cloud.githubusercontent.com/assets/6714237/17643089/6ab6a43c-615f-11e6-8acf-51f032f05bac.png)

**Comment by haoliangyu** [comment]
I have never seen this error at Ubuntu. It's likely about the path difference between Window and Linux, which makes some file inaccessible. Could you post your `public/index.html` to see what happened there?

**Comment by Grandmasg** [comment]
Here is the specific file (renamed)

[index.txt](https://github.com/haoliangyu/angular2-leaflet-starter/files/416660/index.txt)
