### ISSUE TITLE
Insert a new plugin leaflet

### ISSUE THREAD

**Issue by antgrc87** [haoliangyu/angular2-leaflet-starter#12]
Hi, 
i'm new for angular2 and webpack. I have try to insert a plugin for leaflet [(leaflet.markercluster),](https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-0.7) but i have a problem with configuration of this in webpack.config.js. Anyone can help me to understand how to insert the plugin?
thanks in advance

**Comment by haoliangyu** [comment]
Not sure what kind of problem you have encountered. Could you provide more information?

The biggest problem may be from the TypeScript. You will need to import the [type definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/leaflet-markercluster/leaflet-markercluster.d.ts) for `Leaflet.markercluster`, with [typings](https://github.com/typings/typings) or manually.

**Comment by antgrc87** [comment]
as you suggested, i have try to import the type definition file (with the command `typings install github:DefinitelyTyped/leaflet-markercluster/leaflet-markercluster.d.ts --global`).
Unfortunately my problem remains the same, when i try to import (with the command `import {markerClusterGroup} from 'leaflet.markercluster'`) leaflet.markercluster in map.service.ts, i have this error:
error TS2307: Cannot find module 'leaflet.markercluster'

**Comment by haoliangyu** [comment]
Two things are wrong:
* The npm module name is `leaflet-markercluster`, not `leaflet.markercluster`.
* There is no standalone export for `MarkerClusterGroup` and it lives under the `L` namespace.

So import it like this:

``` javascript
import 'leaflet-markercluster';
const markers = new L.MarkerClusterGroup();
```

I haven't check the functionality but the webpack doesn't throw any error. See branch [chore/leafletPlugin](https://github.com/haoliangyu/angular2-leaflet-starter/tree/chore/leafletPlugin).
