### ISSUE TITLE
Application doesn't work with Leaflet 1.0

### ISSUE THREAD

**Issue by jkokh** [haoliangyu/angular2-leaflet-starter#13]
Hi,
could you update leaflet library to version 1.0?

> Sep 27, 2016 — Leaflet 1.0, the fastest, most stable and polished Leaflet release ever, is finally out

**Comment by haoliangyu** [comment]
Yes, it's not compatible at this moment. I will wait until its [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/leaflet/leaflet.d.ts) is done.
