### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by bil-io** [haoliangyu/angular2-leaflet-starter#14]
Are there any plans to update this to LeafLet 1.0?
Is it going to be beneficial at all to move this project to use Angular-CLI? 
Are there any plans to add more features/components? 

I contribute to a project called [SmartCleanWater](https://github.com/smartercleanup/platform) and we use Python and Django. I have suggested to my team to move on to something like React or Angular, and this repo seems like a very good start.

**Comment by haoliangyu** [comment]
Q: Are there any plans to update this to Leaflet 1.0?
A: Yes, as soon as the [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/leaflet/leaflet.d.ts) for 1.0 is done, I will move to Leaflet 1.0.

Q: Is it going to be beneficial at all to move this project to use Angular-CLI? 
A: I personally don't use Angular-CLI so I cannot say how beneficial it would be. I will continue to see if there are more people requesting it.

Q: Are there any plans to add more features/components? 
A: The project has reached its primary goal to show the integration of Angular 2 and Leaflet in a small and clean code set. I currently don't have any plan to add new feature, but I am open to suggestions and PRs. If you think there is any feature good for general users as example, please feel free to open an issue for discussion :)

**Comment by haoliangyu** [comment]
I has moved these questions to the FAQ session.
