### ISSUE TITLE
unable to load map

### ISSUE THREAD

**Issue by vimal1695** [haoliangyu/angular2-leaflet-starter#15]
AppComponent class AppComponent_Host - inline template:0:0 caused by: No provider for ConnectionBackend! ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError Error: No provider for ConnectionBackend!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor]

**Comment by haoliangyu** [comment]
I don't experience this error. Could you provide more information on what you have added and your environment?

**Comment by vimal1695** [comment]
hai...map is  working now...Is there any way to set marker by latitude and longitude?

**Comment by haoliangyu** [comment]
Yes, please take a look at the [L.Marker Documentation](http://leafletjs.com/reference.html#marker), particularly the `setLatLng()` function and the initialization options.

I am closing this issue as the problem has been solved. If you have more question about Leaflet, StackOverflow would be a better place to ask.

**Comment by vimal1695** [comment]
ok thanks
