### ISSUE TITLE
Integrate angular2-leaflet

### ISSUE THREAD

**Issue by alaa-bourouissi** [haoliangyu/angular2-leaflet-starter#16]
I'm new in working with angular 2 and I want to integrate angular2-leaflet in my application based on ng2-bootstrap template (https://github.com/valor-software/ng2-bootstrap) , 
so how To integrate this module  ??

**Comment by Bilal-io** [comment]
Hi @alaa-bourouissi,

If you're new to angular 2, I would suggest playing with it first to understand how it works there are plenty of tutorials out there, or even check the official website, it walks you through creating a simple app. 
After doing that, it'll make sense to you how to import other plugins. 

And your question should go the other way around, the ng2-bootsrap should have the answer for you of how to import and use their plugin to any NG2 project.

**Comment by haoliangyu** [comment]
@Bilal-io Thank you for answering for me :)

@alaa-bourouissi This project is actually using ng2-bootstrap and leaflet together, so you can take a look at how I set up for both. Additionally, ng2-bootstrap and leaflet are two completely independent libraries and the problem of integration with leaflet and ng2-bootstrap actually doesn't exist. They just do things separately. So your focus should be how to use leaflet in Angular 2.

I am closing this issue as it's unrelated to this project. If you have more questions, [StackOverflow](http://stackoverflow.com/) would be a good place to post.
