### ISSUE TITLE
How to deal with Leaflet Plugins

### ISSUE THREAD

**Issue by CoolGeo2016** [haoliangyu/angular2-leaflet-starter#22]
Much of  leaflet plugins without type declaration file in the DefinitelyTyped repository, such as 'esri-leaflet'.
How can I deal with them,except create declaration file by myself.
Can you give some advice?

**Comment by haoliangyu** [comment]
TypeScript is definitely typed so you will still need to provide some sort of type declaration.

1. If you would like to keep the typed leaflet, you could provide a minimal type declaration for your plugin like:

``` typescript
/// <reference types="leaflet" />

declare namespace L {
    // no type definition, just to tell the existence of pluginFunction() at L namespace
    export var pluginFunction: any;
}
```
2. or remove the type declaration of all leaflet things and use it like Javascript

``` typescript
declare var L: any;
```

Source: [Typescript library without tsd file. Cannot instantiate class](http://stackoverflow.com/questions/30833185/typescript-library-without-tsd-file-cannot-instantiate-class?rq=1)

**Comment by haoliangyu** [comment]
Please read my blog [Using an untyped Leaflet plugin in your TypeScript project](https://haoliangyu.github.io/2017/01/25/Using-an-untyped-Leaflet-plugin-in-your-TypeSccript-project/)
