### ISSUE TITLE
Blank Map Problem

### ISSUE THREAD

**Issue by timdog** [haoliangyu/angular2-leaflet-starter#23]
Thank you for creating this starter project. It's been very helpful.

I've created a leaflet module from your code for my Angular2 project and have it displayed with the RouterOutlet using my side navigation. The issue I'm having is in two parts:

1. When I navigate to the leaflet map page and navigate away and come back I would like the map to remember the position and not re-initialize every time. I have not found a way to do this yet.

2. When I navigate away from the leaflet page and then return the map layer is completely blank except for the Navigation and Marker components. The only way I can get the map to show up again is if I pick a different base map. The map then shows up again.

Thank you!

**Comment by haoliangyu** [comment]
@timdog 

1. I set up the code to get the location of your IP address and pan to that location (see [here](https://github.com/haoliangyu/angular2-leaflet-starter/blob/master/public_src/components/app/app.component.ts#L38)). You can delete that line to keep the map intact. Furthermore, you can use a variable to store the previous location before navigation then use `map.setView()` to set it back after your returning.

2. Not sure what happened. Is it possible for you to show some codes, or a simple demo?

**Comment by timdog** [comment]
Thank you. I will look into #1.

#2 I don't really have the means to make a demo and can't share the private repo just yet because of business reasons. Is there a place you recommend for making small demos? I did a little inspection to see what is happening. I am using your exact code and showing the leaflet component in a basic Router Outlet based on some navigation. The first time I browse to it it works fine. If I browse away and come back the map is almost always gone. I looked at the HTML and found that the <div> for leaflet-tile-pane is empty:

<div class="leaflet-pane leaflet-tile-pane"></div>

At this point if I choose a new base map it will populate the map tiles into this <div>. Very strange.

**Comment by haoliangyu** [comment]
That's very strange indeed. If you have time to make a simple demo at [Plunker](https://plnkr.co/) to show the problem, it will be very helpful!

**Comment by timdog** [comment]
I'll give it a shot and get back to you, thanks!

**Comment by haoliangyu** [comment]
I am not sure without knowing how it ran exactly. I will keep this open for now so that people with the problem knows your solution. I will revisit when I have time :)

**Comment by haoliangyu** [comment]
Closing this issue as it should be archived.

**Comment by simonebracaloni** [comment]
I ran in exactly the same issue (#2). 
I had to make a new instance of tileLayer every time I initialize the component.
Did you find why this happen?

**Comment by HonzoBonzo** [comment]
It happens when you are passing layers through input `[leafletLayers]="layers"` and the layers has no `tileLayer` (for example layers initially looks like `layers = [];` in component).

To solve this problem just init layers with instance of tileLayer, eg.:
```
  layers = [
    tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      minZoom: 6,
      attribution:
        '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    }),
  ];
```

then returning to component with map in every route will work fine
