### ISSUE TITLE
Can not get geojson

### ISSUE THREAD

**Issue by jameeshpm** [haoliangyu/angular2-leaflet-starter#28]
"Cannot GET /data/airports.geojson↵"

Could you please help me with this

**Comment by haoliangyu** [comment]
I test the vector tile layer with a new clone and it works for me. Can you elaborate how you set up your project?

**Comment by jameeshpm** [comment]
I have done the following steps
git clone https://github.com/haoliangyu/angular2-leaflet-starter.git leaflet
cd leaflet
npm install
webpack


my destination directory public looks like this 
![image](https://cloud.githubusercontent.com/assets/16596536/22499927/6ecbedc6-e859-11e6-825e-0f0f9e4f5098.png)
 

this is my error console
![image](https://cloud.githubusercontent.com/assets/16596536/22500002/cb697882-e859-11e6-8b8e-dd865f811da8.png)

Thanks for your time

**Comment by haoliangyu** [comment]
Sorry to response late.

From your url, I guess you were running the project using `webpack-dev-server`. Because `webpack-dev-server` only hosted the built files in memory and the geojson file, as an external resource, was not copied into the memory. So it failed to find the file.

There should be no error if you open the `index.html` in your destination directory.

**Comment by 1wiseash** [comment]
I followed all the steps, but I'm still getting the following error after opening public/index.html:
XMLHttpRequest cannot load file:///C:/.../angular2-leaflet-starter-master/public/data/airports.geojson. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Everything else works perfectly, so I'm sure this is an operator error. Thanks for putting this together, btw. Big help.

**Comment by haoliangyu** [comment]
Closing this issue because it seems irrelevant to the project itself.
