### ISSUE TITLE
basic help

### ISSUE THREAD

**Issue by cnlane** [haoliangyu/angular2-leaflet-starter#3]
I am very new to npm, webpack, tsd, etc.  I tried npm install npm -g, npm install tsd -g, npm install webpack-dev-server -g, and even threw in a npm init, and a npm install webpack. I get the error:  cannot find module 'webpack' when I try runing webpack-dev-server.  I've looked at documentation for all the above.  Please help.

**Comment by haoliangyu** [comment]
The documentation isn't very clear.

`webpack-dev-server` is a development tool of [webpack](https://webpack.github.io/) that is used to build the app and set up the development server. To run the `webpack-dev-server` command, please run the following code to install `webpack` and `webpack-dev-server`:

```javascript
npm install webpack -g
npm install webpack-dev-server -g
```

Thanks for pointing out :)

**Comment by haoliangyu** [comment]
I assume this issue was resolved.
