### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by hankaibo** [haoliangyu/angular2-leaflet-starter#30]
Hi.
If I integrated toolbar component, I get the error that
"Cannot read property 'on' of undefined",
I used "rxjs:5.1.5" and "zone.js:0.7.6",
thanks.

**Comment by haoliangyu** [comment]
My guess is that you encountered a racing problem, where the toolbar tried to initialize before the map was created. I have pushed a potential fix for it. Could you try and see if it works for you?

**Comment by hankaibo** [comment]
thank you。


发自坚果手机

Haoliang Yu <notifications@github.com> 于 2017年3月1日，11:50写道：


My guess is that you encountered a racing problem, where the toolbar tried to initialize before the map was created. I have pushed a potential fix for it. Could you try and see if it works for you?

―

**Comment by haoliangyu** [comment]
Close the issue because it should have resolved.
