### ISSUE TITLE
Error: DI Error

### ISSUE THREAD

**Issue by FarhAnAbuBakar** [haoliangyu/angular2-leaflet-starter#31]
Hye..

i have no idea about this error... i integrate your code with my project to display using core ui and encounter this issues...i copied your code exactly and do some changes to match with my code.. 
can u help me to solve it..

![capture1](https://cloud.githubusercontent.com/assets/22883899/23688645/bfefc5e4-03f0-11e7-91a2-a7a369ee4ca9.JPG)
![capture2](https://cloud.githubusercontent.com/assets/22883899/23688669/df38d9b8-03f0-11e7-9562-83a938aa94db.JPG)

![capture](https://cloud.githubusercontent.com/assets/22883899/23688450/a2f6051c-03ef-11e7-814d-d83f0cd78c27.JPG)

**Comment by haoliangyu** [comment]
Sorry to response late. I hope you have figured it out.

From your error message, it seems no provide of something is provided so that it fails to insert that something.. You may check if you forget to set the provider of a service.
