### ISSUE TITLE
I follow all the basic instructions to setup the project

### ISSUE THREAD

**Issue by smgjreinieren** [haoliangyu/angular2-leaflet-starter#5]
But it is not running yet, after i run `webpack` it throws me a shitload of errors where it is not possible to find name: ....

here a few of them:
`ERROR in /Users/Sylvan/Sites/angular2-leaflet-starter/node_modules/angular2/src/common/directives/ng_class.d.ts
(72,35): error TS2304: Cannot find name 'Set'.

ERROR in /Users/Sylvan/Sites/angular2-leaflet-starter/node_modules/angular2/src/common/pipes/async_pipe.d.ts
(25,38): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/Sylvan/Sites/angular2-leaflet-starter/node_modules/angular2/src/http/url_search_params.d.ts
(11,16): error TS2304: Cannot find name 'Map'.

ERROR in /Users/Sylvan/Sites/angular2-leaflet-starter/node_modules/angular2/src/http/headers.d.ts
(43,59): error TS2304: Cannot find name 'Map'.

ERROR in /Users/Sylvan/Sites/angular2-leaflet-starter/node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts
(59,148): error TS2304: Cannot find name 'Promise'`

**Comment by haoliangyu** [comment]
Did you install the type definition files by running `tsd install`? It looks like the type definition file of `es6-shim` is missing.

**Comment by smgjreinieren** [comment]
@haoliangyu yes I did all the steps which describes the installation.

**Comment by smgjreinieren** [comment]
than after sudo tsd install I run `webpack` but it is throwing me the same errors! Can you please help me?

**Comment by haoliangyu** [comment]
Unfortunately, I am not able to reproduce the error. It runs as expected at Ubuntu 15.10 + npm 3.3.6 + Webpack 1.13.1 + tsd 0.6.5. Some similar issues ([#4902](https://github.com/angular/angular/issues/4902), [#7280](https://github.com/angular/angular/issues/7280)) were reported about Angular2 with some potential solutions. You could give a try.

**Comment by smgjreinieren** [comment]
I've updated everything, and now it throws be this error:
`ERROR in Path must be a string. Received undefined
Child extract-text-webpack-plugin:
        + 7 hidden modules
Child extract-text-webpack-plugin:
        + 8 hidden modules
Child extract-text-webpack-plugin:
        + 4 hidden modules
`

**Comment by haoliangyu** [comment]
Ubuntu is my operation system and I don't think that matters. Can you provide the version of `webpack` and `node` you are using? I have seen someone reported similar issues ([#2059](https://github.com/webpack/webpack/issues/2059)) after they upgraded to Node 6.0.

**Comment by haoliangyu** [comment]
Close because of no response
