### ISSUE TITLE
Error loading resource: map.service.ts / Error 404

### ISSUE THREAD

**Issue by smittenspewpew** [haoliangyu/angular2-leaflet-starter#8]
Hi, can you help me out with this?

I am referencing your project to get started with angular 2 and leaflet, but when I try to run it (w/o using webpack) using npm start, the typescript compiler doesn't compile my **map.service.ts** into its equivalent js file, causing it to throw an error 404. But i don't understand why.

Here's a pic of it ->
![image](https://cloud.githubusercontent.com/assets/7857839/16375791/d1845e24-3c8f-11e6-891e-f0375b63abd2.png)

I am pretty sure the tile layers portion are perfectly fine and i've added the source reference for leaflet.d.ts.

Here's the error showing on the browser side -> 
![image](https://cloud.githubusercontent.com/assets/7857839/16375828/049407ec-3c90-11e6-9368-a060002e210b.png)

Thanks a lot

**Comment by haoliangyu** [comment]
There is no `localhost:3000` in my project. Do you have any idea where it came?

**Comment by haoliangyu** [comment]
Close because of no response
