### ISSUE TITLE
Can't start app

### ISSUE THREAD

**Issue by thuanitdn** [haoliangyu/angular2-leaflet-starter#9]
Hi 

I have a problem relate to start application , webpack can't build .

`ERROR in /home/rikeisoft/Tài liệu/angular2/angular2-leaflet-starter-master/public_src/libs.ts
    (5,8): error TS2656: Exported external package typings file '/home/rikeisoft/Tài liệu/angular2/angular2-leaflet-starter-master/node_modules/zone.js/dist/zone.js.d.ts' is not a module. Please contact the package author to update the package definition.`

**Comment by haoliangyu** [comment]
This is an error of zone.js ([#297](https://github.com/angular/zone.js/issues/297)). The fix doesn't seem to be released yet. But the webpack can create bundle even with this error and the app seems to be work for me. Could you test if your webpack can generate js bundle?

**Comment by vimwb** [comment]
I fixed it like this:

added a new file in public_src "lib.d.ts"

contents of "lib.d.ts": 

`
declare module 'zone.js/dist/zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
declare module 'zone.js/dist/long-stack-trace-zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
`

changed "libs.ts"

`
// added two imports
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';

// removed zone.js import
// import 'zone.js';
`

**Comment by haoliangyu** [comment]
@vimwb Thanks for sharing this solution. I have updated the code and added you to the awesome contributor list (if you don't mind).
